# Autogenerated by devscripts/update-version.py

__version__ = '2025.06.26.044441'

RELEASE_GIT_HEAD = 'eff0759705ffcb0c9b9bb59433e9b3acbbd36ddc'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sanek184/yt-dlp'

ORIGIN = 'sanek184/yt-dlp'

_pkg_version = '2025.06.26.044441'
