# Autogenerated by devscripts/update-version.py

__version__ = '2025.06.25.192702'

RELEASE_GIT_HEAD = 'c57412d1f9cf0124adc972a47858ac42b740c61d'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sanek184/yt-dlp'

ORIGIN = 'sanek184/yt-dlp'

_pkg_version = '2025.06.25.192702'
